### ISSUE TITLE
Incompatible pointer type errors

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/mepack#2]
GCC has been updated to v14.0.1 in Fedora rawhide, and this package is failing with incompatible pointer type errors. See the build log here: https://kojipkgs.fedoraproject.org/work/tasks/7663/111857663/build.log

**Comment by Enchufa2** [comment]
FWIW, the same issue was identified by GCC 13, but it was a warning instead of an error, see e.g. https://kojipkgs.fedoraproject.org/work/tasks/7311/111727311/build.log

**Comment by grisuthedragon** [comment]
closed in v1.1.1
